# Configuration Ruff pour DataSens
# Documentation: https://docs.astral.sh/ruff/

# Activer le cache pour accélérer les analyses
cache-dir = ".ruff_cache"

# Longueur de ligne maximale
line-length = 100

# Version Python cible
target-version = "py312"

[lint]
# Sélection des règles à vérifier
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort (imports)
    "N",      # pep8-naming
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "DTZ",    # flake8-datetimez
    "T10",    # flake8-debugger
    "EM",     # flake8-errmsg
    "ISC",    # flake8-implicit-str-concat
    "ICN",    # flake8-import-conventions
    "PIE",    # flake8-pie
    "PT",     # flake8-pytest-style
    "Q",      # flake8-quotes
    "RSE",    # flake8-raise
    "RET",    # flake8-return
    "SIM",    # flake8-simplify
    "PTH",    # flake8-use-pathlib
    "PL",     # pylint
    "RUF",    # ruff-specific rules
]

# Règles à ignorer
ignore = [
    "E501",   # Line too long (géré par formatter)
    "PLR0913", # Too many arguments
    "PLR2004", # Magic value in comparison
]

# Autoriser les auto-fixes
fixable = ["ALL"]
unfixable = []

# Exclure certains dossiers
[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Imports inutilisés OK dans __init__.py
"tests/*.py" = ["S101"]   # Assert OK dans les tests

[format]
# Utiliser des guillemets doubles
quote-style = "double"

# Indentation avec 4 espaces
indent-style = "space"

# Skip magic trailing comma
skip-magic-trailing-comma = false
